// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations need a direct (non-pooled) connection - poolers like Supabase's
    // Supavisor/PgBouncer don't support the session-scoped advisory locks and
    // prepared statements Prisma's migration engine relies on. DIRECT_URL is
    // optional: if unset (e.g. a single non-pooled Postgres in local dev),
    // this just falls back to DATABASE_URL.
    url: process.env["DIRECT_URL"] || process.env["DATABASE_URL"],
  },
});
